### ISSUE TITLE
Cluster property of Test is broken.

### ISSUE THREAD

**Issue by ivandasch** [confluentinc/ducktape#259]
Currently, it takes value from session_context, this is incorrect
```
Traceback (most recent call last):
  File "/opt/ignite-dev/ducktape/ducktape/tests/runner_client.py", line 137, in run
    data = self.run_test()
  File "/opt/ignite-dev/ducktape/ducktape/tests/runner_client.py", line 195, in run_test
    return self.test_context.function(self.test)
  File "/opt/ignite-dev/ducktape/ducktape/mark/_mark.py", line 429, in wrapper
    return functools.partial(f, *args, **kwargs)(*w_args, **w_kwargs)
  File "/opt/ignite-dev/modules/ducktests/tests/ignitetest/tests/self_test.py", line 47, in test_clock_sync
    print("*** available cluster size at test run time: %d" % self.cluster.num_available_nodes())
  File "/opt/ignite-dev/ducktape/ducktape/tests/test.py", line 48, in cluster
    return self.test_context.session_context.cluster
AttributeError: 'SessionContext' object has no attribute 'cluster'
```

**Comment by ivandasch** [comment]
Fixed in #258
