### ISSUE TITLE
Running ducktape with no parameters returns an error

### ISSUE THREAD

**Issue by gwenshap** [confluentinc/ducktape#90]
{code}
Chens-MacBook-Pro:kafka gwen$ ducktape
Traceback (most recent call last):
  File "/usr/local/bin/ducktape", line 9, in <module>
    load_entry_point('ducktape==0.3.2', 'console_scripts', 'ducktape')()
  File "/Library/Python/2.7/site-packages/ducktape-0.3.2-py2.7.egg/ducktape/command_line/main.py", line 139, in main
    tests = loader.discover(args.test_path)
  File "/Library/Python/2.7/site-packages/ducktape-0.3.2-py2.7.egg/ducktape/tests/loader.py", line 108, in discover
    assert type(test_discovery_symbols) == list, "Expected test_discovery_symbols to be a list."
AssertionError: Expected test_discovery_symbols to be a list.
{code}

I'd expect a usage printout (same as ducktape -h)

**Comment by gwenshap** [comment]
Awesome turn around time. Thanks, man. :+1:
